ETL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns=[
	path('' , views.home , name="home"),
]

main/models.py
from django.db import models

# Create your models here.

class Place(models.Model):
    main_place = models.CharField(max_length=100)
    sub_place = models.CharField(max_length=200)
    image = models.ImageField(upload_to="images/", default="/static/img/logo.png")

class Rating(models.Model):
    # user = blah blah blah!
    place_visited = models.ForeignKey(Place,on_delete=models.CASCADE)
    comment = models.TextField(default="This was an awesome place!!")
    rate = models.IntegerField(default=5)

main/forms.py
from django import forms
from . import models
# from .models import GetInTouch

class Message(forms.ModelForm):
	class Meta:
		model=models.SendMessage
		fields = ['message','name','subject','email']#required fields(input by user)

class NewsLetterSubscribe(forms.ModelForm):
	class Meta:
		model = models.NewsLetter
		fields = ['email']

ETL/views.py
from django.http import HttpResponse
from django.shortcuts import render

main/views.py
from django.shortcuts import render
from .models import *
from django.db.models import *
# Create your views here.

def home(request):
	top_places = Place.objects.annotate(avg_rate = Avg('rating')).order_by('-avg_rate')[:4]
	return render(request,'base.html',{'top_places': top_places.all() })

main/templates/base.html
<html>
<head>
    <title>Title</title>
    <style>
        .banner_part{
            background-image: url("/static/img/banner_bg.png")!important;
        }
    </style>
</head>
<body>
    {% extends 'header.html' %}
        {% block content %}
            <section class="banner_part">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-lg-10">
                        <div class="banner_text text-center">
                            <div class="banner_text_iner">
                                <h1> Saintmartine</h1>
                                <p>Let’s start your journey with us, your dream will come true</p>
                                <a href="#" class="btn_1">Discover Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

         <section class="top_place section_padding">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="section_tittle text-center">
                            <h2>Top Places to visit</h2>
                            <p>Waters make fish every without firmament saw had. Morning air subdue. Our. Air very one. Whales grass is fish whales winged.</p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    {% for place in top_places reversed %}
                        <div class="col-lg-6 col-md-6">
                            <div class="single_place">
                                <img src="{{ place.image.url }}" alt="">
                                <div class="hover_Text d-flex align-items-end justify-content-between">
                                    <div class="hover_text_iner">
                                        <a href="#" class="place_btn">travel</a>
                                        <h3>{{ place.main_place }}</h3>
                                        <p>{{  place.sub_place }}</p>
                                        <div class="place_review">
{#                                            TODO : Adding some stars#}
{#                                            {% for x in place.rating_set %}#}
{#                                                <a href="#"><i class="fas fa-star"></i></a>#}
{#                                            {% endfor %}#}
                                            <span>(210 review)</span>
                                        </div>
                                    </div>
                                    <div class="details_icon text-right">
                                        <i class="ti-share"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <a href="#" class="btn_1 text-cnter">Discover more</a>
                </div>

            </div>
        </section>

    {% endblock %}
</body>
</html>

main/templates/blog.html
<html>
<body>
    {% extends 'header.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
    	<section class="blog_area section_padding">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 mb-5 mb-lg-0">
	                    <div class="blog_left_sidebar">
	                        <article class="blog_item">
	                            <div class="blog_item_img">
	                                <img class="card-img rounded-0" src="/static/img/blog/single_blog_1.png" alt="">
	                                <a href="#" class="blog_item_date">
	                                    <h3>1</h3>
	                                </a>
	                            </div>

	                            <div class="blog_details">
	                                <a class="d-inline-block" href="single-blog.html">
	                                    <h2>EAT</h2>
	                                </a>
	                                <p>Rajasthani cuisine was influenced by both the war-like lifestyles of its inhabitants and the availability of ingredients in this arid region.Food that could last for several days and could be eaten without heating was preferred. Scarcity of water and fresh green vegetables have all had their effect on the cooking.</p>
	                            </div>
	                        </article>

	                        <article class="blog_item">
	                            <div class="blog_item_img">
	                                <img class="card-img rounded-0" src="/static/img/blog/single_blog_2.png" alt="">
	                                <a href="#" class="blog_item_date">
	                                    <h3>2</h3>
	                                </a>
	                            </div>

	                            <div class="blog_details">
	                                <a class="d-inline-block" href="single-blog.html">
	                                    <h2>Fairs And Festivals</h2>
	                                </a>
	                                <p>Rajasthan packs the essence of Incredible India in 1 state. And the experience of Rajasthan is never complete unless you have a taste of the myriad fairs and festivals that it has to offer. They are a celebration of life, culture, heritage, and nature, in true Rajasthani style</p>
	                            </div>
	                        </article>

	                        <article class="blog_item">
	                            <div class="blog_item_img">
	                                <img class="card-img rounded-0" src="/static/img/blog/single_blog_3.png" alt="">
	                                <a href="#" class="blog_item_date">
	                                    <h3>3</h3>
	                                </a>
	                            </div>

	                            <div class="blog_details">
	                                <a class="d-inline-block" href="single-blog.html">
	                                    <h2>Shopping</h2>
	                                </a>
	                                <p>Shopping in Rajasthan is about colorful trinkets, leather goods, spices and even royal jewelry; which makes it one of the best things to do in Rajasthan. The state has made the world go gaga over its artistry, along with its splendid monuments that speak of a legendary past. People come here from across the world, and make their way to home with double the baggage.</p>
	                            </div>
	                        </article>

	                        <article class="blog_item">
	                            <div class="blog_item_img">
	                                <img class="card-img rounded-0" src="/static/img/blog/single_blog_4.png" alt="">
	                                <a href="#" class="blog_item_date">
	                                    <h3>4</h3>
	                                </a>
	                            </div>
	                            <div class="blog_details">
	                                <a class="d-inline-block" href="single-blog.html">
	                                    <h2>Luxury On Wheels</h2>
	                                </a>
	                                <p>In just 8 days your traverse across the huge terrain of Rajasthan and Agra and soak in the culture while being our pampered guest. You get, spacious Deluxe cabins with attached bathrooms, a personal butler, amenities that include 2 restaurants, a lounge bar and a spa.</p>
	                            </div>
	                        </article>

	                        <article class="blog_item">
	                            <div class="blog_item_img">
	                                <img class="card-img rounded-0" src="/static/img/blog/single_blog_5.png" alt="">
	                                <a href="#" class="blog_item_date">
	                                    <h3>5</h3>
	                                </a>
	                            </div>

	                            <div class="blog_details">
	                                <a class="d-inline-block" href="single-blog.html">
	                                    <h2>Highlights</h2>
	                                </a>
	                                <p>The princely state of Rajasthan is famed for its glorious past, rich culture, and splendid heritage. The best palaces in Rajasthan – beautiful and grand – stand as testament to this fact. These palaces, their architecture, and their old walls tell stories of the glorious past of the state. Some of the palaces are so grand and royal that they’ve been converted into heritage hotels, so that tourists can get to experience the lifestyle of the royals.</p>
	                            </div>
	                        </article>
	                    </div>
	                </div>
	              	            </div>
	        </div>
    	</section>
    {% endblock %}
</body>
</html>

main/templates/contact.html
<html>
<body>
    {% extends 'header.html' %}
    {% load crispy_forms_tags %}
        {% block content %}
	        <section class="breadcrumb breadcrumb_bg">
		        <div class="container">
		            <div class="row">
		                <div class="col-lg-12">
		                    <div class="breadcrumb_iner">
		                        <div class="breadcrumb_iner_item text-center">
		                            <h2>contact</h2>
		                            <p>home . contact</p>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
	    	</section>
	    	<section class="contact-section">
		        <div class="container">
		            <div class="d-none d-sm-block mb-5 pb-4">
		                <div id="map" style="height: 480px;"></div>
		                <script>
		                    function initMap() {
		                        var uluru = {
		                            lat: -25.363,
		                            lng: 131.044
		                        };
		                        var grayStyles = [{
		                            featureType: "all",
		                            stylers: [{
		                                saturation: -90
		                            }, {
		                                lightness: 50
		                            }]
		                        }, {
		                            elementType: 'labels.text.fill',
		                            stylers: [{
		                                color: '#ccdee9'
		                            }]
		                        }];
		                        var map = new google.maps.Map(document.getElementById('map'), {
		                            center: {
		                                lat: 19.1232,
		                                lng: 72.8361   
		                            },
		                            zoom: 9,
		                            styles: grayStyles,
		                            scrollwheel: false
		                        });
		                    }
		                </script>
		                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap">
		                </script>

		            </div>

		            <div class="row">
		                <div class="col-12">
		                    <h2 class="contact-title">Get in Touch</h2>
		                </div>
		                <div class="col-lg-8">

                            <form class="form-contact contact_form" method="POST" id="contactForm" novalidate="novalidate">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">

                                            <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder='Enter Message'></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder='Enter your name'>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder='Enter email address'>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder='Enter Subject'>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-3">
                                    <button type="submit" class="button button-contactForm btn_1">Send Message</button>
                                </div>
                            </form>

		                </div>
		                <div class="col-lg-4">
		                    <div class="media contact-info">
		                        <span class="contact-info__icon"><i class="ti-home"></i></span>
		                        <div class="media-body">
		                            <h3>Amer Fort</h3>
		                            <p>Jaipur,Rajasthan,India</p>
		                        </div>
		                    </div>
		                    <div class="media contact-info">
		                        <span class="contact-info__icon"><i class="ti-tablet"></i></span>
		                        <div class="media-body">
		                            <h3>00 (440) 9865 562</h3>
		                            <p>Mon to Fri 9am to 6pm</p>
		                        </div>
		                    </div>
		                    <div class="media contact-info">
		                        <span class="contact-info__icon"><i class="ti-email"></i></span>
		                        <div class="media-body">
		                            <h3>rajasthantourism@gmail.com</h3>
		                            <p>Send us your query anytime!</p>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
    		</section>
        {% endblock %}
</body>
</html>

main/templates/gallery.html
{% extends 'header.html' %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
    <!-- Compiled and minified CSS -->
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">#}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">#}
    <!-- Compiled and minified JavaScript -->
{#    <link rel="stylesheet" href="/static/css/style1.css">#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>#}
{#  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>#}
</head>
<body>
  {% block content%}
    <div class="row">
    <div class="column col-s-12 col-l-3 col-xl-3">
      <img src="/static/images/1.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/2.jpg" style="width:100% ; padding-top:10px!important;">
      <img src="/static/images/3.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/4.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/5.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/6.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/7.jpg" style="width:100%; padding-top:10px!important;">
    </div>
    <div class="column col-s-12 col-l-3 col-xl-3">
      <img src="/static/images/8.jpg" style="width:100% ; padding-top:10px!important;">
      <img src="/static/images/9.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/10.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/11.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/12.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/13.jpg" style="width:100%; padding-top:10px!important;">
    </div>  
    <div class="column col-s-12 col-l-3 col-xl-3">
      <img src="/static/images/14.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/15.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/16.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/17.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/18.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/19.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/20.jpg" style="width:100%; padding-top:10px!important;">
    </div>
    <div class="column col-s-12 col-l-3 col-xl-3">
      <img src="/static/images/21.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/22.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/23.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/24.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/25.jpg" style="width:100%; padding-top:10px!important;">
      <img src="/static/images/26.jpg" style="width:100%; padding-top:10px!important;">
    </div>
  </div>
  {% endblock %}
</body>
</html>

main/templates/header.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/themify-icons.css">
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">
    <link rel="stylesheet" href="/static/css/gijgo.min.css">
    <link rel="stylesheet" href="/static/css/nice-select.css">
    <link rel="stylesheet" href="/static/css/slick.css">
    <link rel="stylesheet" href="/static/css/style.css">

</head>
<body>

    <header class="main_menu">
        <div class="sub_menu">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-sm-12 col-md-6">
                        <div class="sub_menu_right_content">
                            <span>Top destinations</span>
                            <a href="/asia">Asia</a>
                            <a href="/europe">Europe</a>
                            <a href="/america">America</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-12 col-md-6">
                        <div class="sub_menu_social_icon">
                            <a href="#"><i class="flaticon-facebook"></i></a>
                            <a href="#"><i class="flaticon-twitter"></i></a>
                            <a href="#"><i class="flaticon-skype"></i></a>
                            <a href="#"><i class="flaticon-instagram"></i></a>
                            <span><a><i class="flaticon-phone-call"></i>+880 356 257 142</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main_menu_iner">
            <div class="container">
                <div class="row align-items-center ">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg navbar-light justify-content-between">
                            <a class="navbar-brand" href="index.html"> <img src="/static/img/logo.png" alt="logo"> </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse main-menu-item justify-content-center"
                                id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="index.html">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="about.html">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="packages.html">packages</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown"
                                            role="button" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                            Blog
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="blog.html">Blog</a>
                                            <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                        </div>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                            role="button" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                            pages
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                            <a class="dropdown-item" href="top_place.html">top place</a>
                                            <a class="dropdown-item" href="tour_details.html">tour details</a>
                                            <a class="dropdown-item" href="elements.html">Elements</a>
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="contact.html">Contact</a>
                                    </li>
                                </ul>
                            </div>
                            <a href="#" class="btn_1 d-none d-lg-block">book now</a>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {% block content %}
    {% endblock %}

    <!-- jquery plugins here-->
    <script src="/static/js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="/static/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- magnific js -->
    <script src="/static/js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="/static/js/owl.carousel.min.js"></script>
    <!-- masonry js -->
    <script src="/static/js/masonry.pkgd.js"></script>
    <!-- masonry js -->
    <script src="/static/js/jquery.nice-select.min.js"></script>
    <script src="/static/js/gijgo.min.js"></script>
    <!-- contact js -->
    <script src="/static/js/jquery.ajaxchimp.min.js"></script>
    <script src="/static/js/jquery.form.js"></script>
    <script src="/static/js/jquery.validate.min.js"></script>
    <script src="/static/js/mail-script.js"></script>
    <script src="/static/js/contact.js"></script>
    <!-- custom js -->
    <script src="/static/js/custom.js"></script>
</body>
</html>

main/templates/order.html
<html>
<head>
    <title>Home</title>
</head>
<body>
    {% extends 'header.html' %}
        {% block content %}
         <section class="top_place section_padding">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="section_tittle text-center">
                            <h2>Top Places to visit</h2>
                            <p>Rajasthan, also known as the ‘Land of Maharajas’, is seemingly one of the most Instagrammable places in India. Rows of majestic forts and palaces, centuries-old architecture, colourful façades, scenic lakes, rugged landscapes, lively festivals and culture, lip-smacking traditional cuisine, golden sunsets and sand dunes – this largest state of India is brimming with a vibrancy that will leave you clicking that shutter non-stop</p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    {% for place in places reversed %}
                        <div class="col-lg-6 col-md-6">
                            <div class="single_place">
                                <img src="{{ place.image.url }}" alt="">
                                <div class="hover_Text d-flex align-items-end justify-content-between">
                                    <div class="hover_text_iner">
                                        <a href="{% url 'main:packages' %}" class="place_btn">travel</a>
                                        <h3>{{ place.main_place }}</h3>
                                        <p>{{  place.sub_place }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </section>

    {% endblock %}
</body>
</html>

main/templates/package.html
<html>
<head>
    <title>Places</title>
    <style>
        .banner_part{
            background-image: url("/static/img/home-banner.jpg")!important;
        }
    </style>
</head>
<body>
    {% extends 'header.html' %}
    {% block content %}
    <div class="container">
        {%  for place in places  %}
                {% if forloop.counter0|divisibleby:3 %} <div class="row"> {%  endif %}
                    <div class="col-lg-4 col-sm-6">
                        <div class="single_ihotel_list">
                            <img src="{{place.image.url}}" alt="">
                            <div class="hotel_text_iner">
                                <h3> <a href="#">{{place.main_place}}</a></h3>
                                <div class="place_review">
                                </div>
                                <p>{{place.sub_place}}</p>
                                <h5>From <span> Rupees {{place.cost}}</span></h5>
                            </div>
                        </div>
                    </div>
                {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><!-- row closing --><hr>{%  endif %}
        {%  endfor %}
    </div>
{% endblock %}
</body>
</html>